### ISSUE TITLE
Organize API returns 404

### ISSUE THREAD

**Issue by johnc2k** [shawly/docker-nut#9]
Calling `http://localhost:9000/api/organize` (with the appropriate host) returns `404` error (and does not organize files).
The `scan` API however works fine.

Tested both the `latest` and `edge` releases on amd64.

**Comment by johnc2k** [comment]
Seems if the `keys.txt` is not populated this results in the above error

**Comment by shawly** [comment]
Yeah I can reproduce this on `edge` when I use my old `keys.txt`, with my old `keys.txt` I don't have this issue when I use `latest`.
After I dumped my keys again with Lockpick I can solve this problem on `edge` as well.

This issue also happens with the `keys.txt` found on the net by googling. So I guess people will have to use `latest` or `v3.3` if they didn't dump their own keys.

Nonetheless, this is an issue related to NUT itself so stuff like this should be reported on [their GitHub](https://github.com/blawar/nut/issues) in the future because I cannot fix issues with NUT itself in my Docker image.
